### ISSUE TITLE
Draft Mission/Vision/Values statement

### ISSUE THREAD

**Issue by froi** [Code4PuertoRico/Code4PR#11]
As an organization we need to draft an official Mission, vision, and values statements.

This will help keep us honest and on course. It will also help us grow and start establishing a organizational identity and culture.

[We already started brainstorming this](https://app.mural.co/t/code4puertorico5920/m/code4puertorico5920/1593280370150/193c0840bab607f5cf09126a338c06eac14f7c54).

**Comment by froi** [comment]
Empece un [borrador](https://docs.google.com/document/d/1gNRB27wE37dssfC_H6mETdQb5o0ClISkXAPnKRwCYYg).

**Comment by froi** [comment]
Despues de varias horas de estar discutiendo este documento hemos llegado a las parte de valores.

Queremos tomarnos nuestro tiempo y verdaderamente analizar cuales son.

@albertico a sugerido leer lo siguiente para retomar esta conversación:

- [Finding the Right Company Values](https://softwareengineeringdaily.com/2018/10/26/show-summary-engineering-values-with-lynne-tye/) -- At the top of the article there is a link to a podcast episode about Engineering Values which I'm listening to.
- [On Crafting Engineering Values at VTS](https://buildingvts.com/on-crafting-engineering-values-at-vts-e2d76152634b)
- [Figma's engineering values](https://www.figma.com/blog/figmas-engineering-values/)
- [Make Your Values Mean Something (from HBR)](https://hbr.org/2002/07/make-your-values-mean-something)
- [How To Define Your Organization's Values (Forbes contributor)](https://www.forbes.com/sites/gregsatell/2015/11/27/how-to-define-your-organizations-values/)
- [USDS' mission and values](https://www.usds.gov/mission) -- I saw these values evolve and the teams I was part of went through different stages where the USDS values were fundamental to frame our decisions and path forward, so I'm happy to talk about that if interested.
- [18 Core Company Values That Will Shape Your Culture & Inspire Your Employees](https://blog.hubspot.com/marketing/company-values) -- This article mentions the values of American Express, Google, Coca Cola, Whole Foods.
- [Amazon's Leadership Principles](https://www.amazon.jobs/en/principles) -- These may not be considered exactly "values", but still worth reading.

La sugerencia es de retomar esto el proximo sabado 18 de julio.

**Comment by albertico** [comment]
Después de leer [los artículos y ejemplos que encontramos sobre el tema](https://github.com/Code4PuertoRico/Code4PR/issues/11#issuecomment-657124774), de reflexionar sobre la evolución de C4PR desde que lo fundamos y de ir sobre el ["brainstorming"](https://app.mural.co/t/code4puertorico5920/m/code4puertorico5920/1593280370150/193c0840bab607f5cf09126a338c06eac14f7c54) y el [borrador](https://docs.google.com/document/d/1gNRB27wE37dssfC_H6mETdQb5o0ClISkXAPnKRwCYYg) de nuestra misión, redacté un borrador inicial de valores a utilizar en nuestra discusión.

Dado que las fuentes y ejemplos utilizados fueron en inglés, este primer borrador también está redactado en inglés. Tengo que traducirlos a español y actualizarlos según sea necesario para garantizar que hagan sentido en ambos idiomas.

---

## Code 4 Puerto Rico Values

These values represent the Code 4 Puerto Rico community. We adhere to them and they serve as our guiding principles both in good and bad times. They are intended to help us make decisions as well as to remind ourselves of the team that we wish to be.

Our values describe who we are, how we work together and how we build products. They represent choices that are directly related to our mission. They determine how Code 4 Puerto Rico will pursue its purpose.

**We welcome everyone to participate**
In order to design solutions that represent everyone, we must involve individuals from all professional backgrounds, creed, sexual orientation, gender identity and social level. Building technology solutions is not the sole work of developers. And no matter where you live or where you are, if you can virtually collaborate with our initiatives, that’s all you need to participate.

**We think of people first (We are people first)**
The best products and solutions aren’t created in a vacuum. We need empathy and curiosity to understand the problems, ideate solutions and test our hypothesis. We must avoid making assumptions and listen to the individuals involved as much as possible. Only then we will start creating solutions that really address people’s needs.

**We strive to build products, not push code**
Thoughtful solutions are more than code. Our decision making is heavily influenced by regulation, people’s concerns and their needs. We’re not just pushing code, we’re solving people’s problems through product experiences. The more interdisciplinary and diverse the teams working on our initiatives are, the more inclusive our solutions will be.

**We ~~must~~ prioritize impact**
We can only solve so many problems at once. And there will also be so many volunteers willing to contribute to any initiative. Things are built with a shelf-life in mind and that’s okay. In order to develop solutions that are sustainable, we must focus on the things that matter to the most people. No matter what the problem we are solving is, if we truly believe it’s important, we must think of the most impactful way to solve it with the means and resources available to us.

**We work in the open**
We rely heavily on open source technologies and data to execute our mission. As such, we advocate for the use and contribution to open source projects, open standards and open data initiatives. We not only promote the adoption of these open technologies, but we also expect that our projects and initiatives are executed in the open. We believe that in order to create a culture of feedback, foster collaboration, build trust and reach sustainability, we must be open and transparent.

**We ~~must~~ iterate**
No solution is perfect or comprehensive enough ~~, and perfect is the enemy of good~~. Speed matters and time is scarce, especially for any volunteer driven organization. Feedback, collaboration and culture change need to be revisited and will strengthen through time. Consequently, our projects must continually iterate. We work in an agile fashion and truly believe that progress is made of small wins that get delivered incrementally.

**Comment by froi** [comment]
Love this!!! ❤️ 

Añadir estos valores a la version inicial de nuestra mision, vision y valores. Los tenemos que traducir a español y ver como tenemos que editarlos.

**Comment by froi** [comment]
Creo que al traducir los valores al español podemos cerrar este issue.

Tenemos que abrir uno para la traduccion al ingles.

**Comment by froi** [comment]
Los valores ha sido traducidos en el documento inicial.

Ademas hemos creado issues para tomar feedback de los valores;

- https://github.com/Code4PuertoRico/Code4PR/issues/38
- https://github.com/Code4PuertoRico/Code4PR/issues/39

Closing this out.
